// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sciensoft.Samples.Products.Api.Infrastructure.Repository;

namespace Sciensoft.Samples.Products.Api.Infrastructure.Migrations
{
    [DbContext(typeof(ProductsDbContext))]
    [Migration("20190410154610_Index and Unique")]
    partial class IndexandUnique
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("Sciensoft.Samples.Products.Api.Infrastructure.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<DateTime>("LastUpdated");

                    b.Property<string>("Name");

                    b.Property<string>("PhotosReference");

                    b.Property<decimal>("Price");

                    b.Property<int>("Version");

                    b.HasKey("Id")
                        .HasName("PK_ProductId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
